name: Build all

on:
  workflow_dispatch:
    inputs:
      branch:
        description: PDFium branch
        required: false
        default: main
      version:
        description: PDFium version
        required: false
        default: ""
      is_debug:
        description: Is debug
        type: boolean
        required: false
        default: false
      release:
        description: Publish GitHub release
        type: boolean
        required: false
        default: false

jobs:
  linux_arm64:
    name: Linux ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: arm64
      enable_v8: false

  linux_x64:
    name: Linux x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: linux
      target_cpu: x64
      enable_v8: false

  mac_arm64:
    name: macOS ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: arm64
      enable_v8: false

  mac_x64:
    name: macOS x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: mac
      target_cpu: x64
      enable_v8: false

  win_arm64:
    name: Windows ARM64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: arm64
      enable_v8: false

  win_x64:
    name: Windows x64
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      is_debug: ${{ github.event.inputs.is_debug == 'true' }}
      target_os: win
      target_cpu: x64
      enable_v8: false

  mac_univ:
    name: macOS univ
    needs:
      - mac_arm64
      - mac_x64
    uses: ./.github/workflows/mac-univ.yml
    with:
      artifact_x64: ${{ needs.mac_x64.outputs.artifact }}
      artifact_arm64: ${{ needs.mac_arm64.outputs.artifact }}

  publish:
    name: Publish Release
    if: startsWith(github.event.inputs.branch, 'chromium/') && github.event.inputs.version && github.event.inputs.release == 'true'
    runs-on: ubuntu-latest
    needs:
      - linux_arm64
      - linux_x64
      - mac_arm64
      - mac_univ
      - mac_x64
      - win_arm64
      - win_x64
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create tarballs
        run: |
          for DIR in pdfium-*; do
            echo "::group::$DIR"
            (cd $DIR; tar czf ../$DIR.tgz *)
            echo "::endgroup::"
          done
      - name: Write release body
        run: echo 'This version was built with branch `${{ github.event.inputs.branch }}` of PDFium' > RELEASE.md
      - name: Get changes
        continue-on-error: true
        run: |
          CURRENT_REV=${{ github.event.inputs.branch }}
          PREVIOUS_REV=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name")
          git clone -b "${{ github.event.inputs.branch }}" https://pdfium.googlesource.com/pdfium.git
          cat <<END >> RELEASE.md
          ### Changes
          Commits between \`$PREVIOUS_REV\` and \`$CURRENT_REV\`:
          END
          git -C "pdfium" log origin/${PREVIOUS_REV}.. --pretty=format:'* [%s](https://pdfium.googlesource.com/pdfium/+/%H)' >> RELEASE.md
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          bodyFile: RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PDFium ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.branch }}
          artifacts: "pdfium-*.tgz"
